#!/usr/bin/env bash
set -Eeuo pipefail

script_path="$(readlink -f -- "${BASH_SOURCE[0]}")"
script_dir="$(cd -- "$(dirname -- "$script_path")" && pwd -P)"

exec "$script_dir/../bin/ws-man" start "$@"
